### ISSUE TITLE
[NtS] Correct reference to latest NtS commission regulation in NtS documents section

### ISSUE THREAD

**Issue by ChristophPlasil** [cesniti/ris_public_files#17]
Von: Oudenes, Peter (VWM)
Gesendet: Donnerstag, 18. Februar 2021 22:20
An: Plasil Christoph ; 'Raphaël Le Guillou' 
Betreff: FW: CESNI website

Dear Christoph and Raphael,

is there a special reason why the commission regulation 2018/2032 on CESNI-TI RIS | NOTICE TO SKIPPERS NTS DOCUMENTATION (https://ris.cesni.eu/332-en.html) refers to the 2007 commission regulation instead of 2018.
The underlines part contains this reference.

Peter

STANDARDS NTS VERSION 4.0

The Commission Regulation (EU) 2018/2032 of 20 November 2018 amending Commission Regulation (EC) No. 416/2007 of 22 March 2007. This concerns the technical specifications for Notices to Skippers as referred to in Article 5 of Directive 2005/44/EC of the European Parliament and of the Council on harmonised river information services (RIS) on inland waterways in the Community with the objective to support the safety of navigation and voyage planning.

**Comment by larhape** [comment]
The issue has been fixed on the website.

Please confirm everything is OK.

**Comment by ChristophPlasil** [comment]
Thanks, yes now the link works as expected.
